---
driver:
  name: vagrant
  provider: vmware_fusion
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

verifier:
  name: pester

platforms:
#  - name: ubuntu-14.04
#  - name: centos-7.1
  - name: win2008r2
    os_type: windows
    driver:
      box: chef/windows-server-2008r2-standard
    provisioner:
      require_chef_omnibus: 12
  - name: win2012r2
    os_type: windows
    driver_config:
      box: win2012r2-nocm
    provisioner:
      require_chef_omnibus: 12

suites:
  - name: default
    run_list:
      - recipe[svn_issue::default]
